apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wordpress
  name: port-forward-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  # verbs: ["get", "list"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
