apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: port-forward-role-binding
  namespace: wordpress
subjects:
- kind: User
  name: port-forward-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: port-forward-role
  apiGroup: rbac.authorization.k8s.io